global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'leanbalancer'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'backend1'
    static_configs:
      - targets: ['localhost:9001']

  - job_name: 'backend2'
    static_configs:
      - targets: ['localhost:9002']

  - job_name: 'backend3'
    static_configs:
      - targets: ['localhost:9003']
